name: backend-ci-pipeline
on:
  branch:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  build:
    name: Build Docker 
    runs-on:  ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          path: "financial-go"
      - name: Build docker containers
        run: |
          echo  ---Building and starting up docker---
          docker-compose -f ./financial-go/docker-compose.test.yml -p api-test up -d
          echo  ---Containers up---
      - name: Run tests
        run: |
          echo  ---Running test cases---
          docker-compose -f ./financial-go/docker-compose.test.yml -p api-test up --build --exit-code-from backend
          echo  ---Completed test cases
